[project]
name = "stata-multi-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.16.4",
    "nbformat>=5.10.4",
    "ruff>=0.13.2",
]
